export type PlanTier = 'free' | 'professional' | 'expert';

export interface ToolItem {
  id: string;
  plan: PlanTier;
  routeFr: string;
  routeEn: string;
  titleFr: string;
  titleEn: string;
  descFr: string;
  descEn: string;
  icon?: string;
}

export const TOOLS_CATALOG: ToolItem[] = [
  {
    id: 'financial-assistant',
    plan: 'free',
    routeFr: '/assistant-financier',
    routeEn: '/financial-assistant',
    titleFr: 'Assistant financier',
    titleEn: 'Financial assistant',
    descFr: 'Recevez des conseils généraux et des étapes guidées pour organiser vos premières actions.',
    descEn: 'Get general guidance and step-by-step help to organize your first actions.',
    icon: 'help-circle',
  },
  {
    id: ‘emergency-kit’,
    plan: ‘free’,
    routeFr: ‘/trousse’,
    routeEn: ‘/kit’,
    titleFr: ‘Trousse urgence et inaptitude’,
    titleEn: ‘Emergency and incapacity kit’,
    descFr: ‘Préparez vos 3 formulaires officiels (A, B, C) en format PDF fillable — 98 pages à compléter et imprimer.’,
    descEn: ‘Prepare your 3 official forms (A, B, C) as fillable PDFs — 98 pages to complete and print.’,
    icon: ‘shield’,
  },
  {
    id: 'expense-planning',
    plan: 'free',
    routeFr: '/planification-depenses',
    routeEn: '/expense-planning',
    titleFr: 'Planifier mes dépenses',
    titleEn: 'Plan my expenses',
    descFr: 'Planifiez vos dépenses mensuelles et repérez les économies rapides.',
    descEn: 'Plan your monthly expenses and spot quick savings.',
    icon: 'wallet',
  },
  {
    id: 'rrq-quick-compare',
    plan: 'free',
    routeFr: '/rrq-quick-compare',
    routeEn: '/rrq-quick-compare',
    titleFr: 'Comparer la RRQ à 60, 65 ou 70 ans',
    titleEn: 'Compare QPP at 60, 65 or 70',
    descFr: 'Voyez rapidement la différence entre demander votre RRQ plus tôt ou plus tard.',
    descEn: 'Quickly compare the impact of starting your QPP earlier or later.',
    icon: 'scales',
  },
  {
    id: 'rrq-delay-simulator',
    plan: 'free',
    routeFr: '/rrq-delay-simulator',
    routeEn: '/rrq-delay-simulator',
    titleFr: 'Reporter la RRQ de quelques mois',
    titleEn: 'Delay QPP by a few months',
    descFr: 'Simulez l’effet d’un report de quelques mois sur votre rente.',
    descEn: 'Simulate the effect of delaying your pension by a few months.',
    icon: 'clock',
  },
  {
    id: 'advanced-performance-calculator',
    plan: 'professional',
    routeFr: '/calculette-rendement-avancee',
    routeEn: '/advanced-performance-calculator',
    titleFr: 'Faire croître mon épargne',
    titleEn: 'Grow my savings',
    descFr: 'Comparez différents rendements pour voir comment votre épargne peut évoluer.',
    descEn: 'Compare different return assumptions to see how your savings could grow.',
    icon: 'line-chart',
  },
  {
    id: 'four-percent-rule',
    plan: 'professional',
    routeFr: '/regle-4-pourcent',
    routeEn: '/four-percent-rule',
    titleFr: 'Règle du 4 %',
    titleEn: '4% rule',
    descFr: 'Estimez un retrait annuel prudent à partir de votre capital.',
    descEn: 'Estimate a prudent annual withdrawal from your capital.',
    icon: 'percent',
  },
  {
    id: 'optimal-allocation',
    plan: 'professional',
    routeFr: '/module-allocation-optimale',
    routeEn: '/module-allocation-optimale',
    titleFr: 'Répartir mes placements',
    titleEn: 'Set my investment mix',
    descFr: 'Trouvez une répartition plus adaptée à votre tolérance au risque.',
    descEn: 'Find an allocation that better fits your risk tolerance.',
    icon: 'pie-chart',
  },
  {
    id: 'celiapp',
    plan: 'professional',
    routeFr: '/celiapp',
    routeEn: '/celiapp',
    titleFr: 'CELIAPP',
    titleEn: 'FHSA',
    descFr: 'Planifiez vos cotisations et retraits CELIAPP efficacement.',
    descEn: 'Plan FHSA contributions and withdrawals effectively.',
    icon: 'banknote',
  },
  {
    id: 'asset-consolidation',
    plan: 'professional',
    routeFr: '/module-consolidation-actifs',
    routeEn: '/module-consolidation-actifs',
    titleFr: 'Regrouper mes placements',
    titleEn: 'Group my investments',
    descFr: 'Regroupez vos comptes pour simplifier votre suivi et vos décisions.',
    descEn: 'Group your accounts to simplify tracking and decision-making.',
    icon: 'merge',
  },
  {
    id: 'financial-consolidation',
    plan: 'professional',
    routeFr: '/consolidation-financiere',
    routeEn: '/financial-consolidation',
    titleFr: 'Simplifier mes finances',
    titleEn: 'Simplify my finances',
    descFr: 'Réduisez la complexité et les frais liés à plusieurs institutions.',
    descEn: 'Reduce complexity and fees across multiple institutions.',
    icon: 'layers',
  },
  {
    id: 'healthcare-costs',
    plan: 'professional',
    routeFr: '/couts-sante',
    routeEn: '/healthcare-costs',
    titleFr: 'Prévoir mes coûts de santé',
    titleEn: 'Plan my healthcare costs',
    descFr: 'Projetez des dépenses de santé réalistes dans votre budget.',
    descEn: 'Project realistic healthcare expenses in your budget.',
    icon: 'heart-pulse',
  },
  {
    id: 'excess-liquidity-detector',
    plan: 'professional',
    routeFr: '/detecteur-liquidites-excessives',
    routeEn: '/detecteur-liquidites-excessives',
    titleFr: 'Détecter trop de liquidités',
    titleEn: 'Detect excess cash',
    descFr: 'Identifiez les montants dormants et réallouez-les intelligemment.',
    descEn: 'Identify idle cash and reallocate it more efficiently.',
    icon: 'droplet',
  },
  {
    id: 'tax-impact-65',
    plan: 'professional',
    routeFr: '/calculateur-impact-fiscal-65',
    routeEn: '/calculateur-impact-fiscal-65',
    titleFr: 'Ce qui change à 65 ans',
    titleEn: 'What changes at 65',
    descFr: 'Voyez les crédits et avantages fiscaux qui apparaissent à 65 ans.',
    descEn: 'See the tax credits and benefits that appear at age 65.',
    icon: 'calendar',
  },
  {
    id: 'ferr-optimization',
    plan: 'professional',
    routeFr: '/optimisation-ferr',
    routeEn: '/ferr-optimization',
    titleFr: 'Retirer de mon FERR',
    titleEn: 'Withdraw from my RRIF',
    descFr: 'Testez vos retraits FERR pour limiter l’impôt sur plusieurs années.',
    descEn: 'Test RRIF withdrawal strategies to limit taxes over time.',
    icon: 'sliders',
  },
  {
    id: 'multi-source-tax-optimization',
    plan: 'professional',
    routeFr: '/optimisation-fiscale-multi-sources',
    routeEn: '/multi-source-tax-optimization',
    titleFr: 'Payer moins d’impôt à la retraite',
    titleEn: 'Pay less tax in retirement',
    descFr: 'Coordonnez vos retraits et vos revenus pour réduire l’impôt total.',
    descEn: 'Coordinate withdrawals and income sources to reduce total tax.',
    icon: 'calculator',
  },
  {
    id: 'cpp-timing',
    plan: 'professional',
    routeFr: '/optimisation-timing-cpp',
    routeEn: '/cpp-timing',
    titleFr: 'Choisir le bon moment pour la RRQ/CPP',
    titleEn: 'Choose the right time for QPP/CPP',
    descFr: 'Comparez les âges possibles pour demander votre RRQ ou votre CPP.',
    descEn: 'Compare possible ages to start your QPP or CPP.',
    icon: 'timer',
  },
  {
    id: 'longevity-planning',
    plan: 'professional',
    routeFr: '/planification-longevite',
    routeEn: '/longevity-planning',
    titleFr: 'Faire durer mon argent plus longtemps',
    titleEn: 'Make my money last longer',
    descFr: 'Testez si votre argent peut durer selon différents scénarios de longévité.',
    descEn: 'Test whether your money can last under different longevity scenarios.',
    icon: 'dna',
  },
  {
    id: 'dynamic-withdrawal',
    plan: 'expert',
    routeFr: '/planification-retrait-dynamique',
    routeEn: '/dynamic-withdrawal',
    titleFr: 'Ajuster mes retraits dans le temps',
    titleEn: 'Adjust my withdrawals over time',
    descFr: 'Ajustez vos retraits selon les marchés et vos objectifs.',
    descEn: 'Adjust withdrawals according to markets and your goals.',
    icon: 'activity',
  },
  {
    id: 'inflation-protection',
    plan: 'expert',
    routeFr: '/centre-protection-inflation',
    routeEn: '/centre-protection-inflation',
    titleFr: 'Protection contre l’inflation',
    titleEn: 'Inflation protection',
    descFr: 'Protégez votre plan contre la hausse du coût de la vie.',
    descEn: 'Protect your plan against a rising cost of living.',
    icon: 'shield-half',
  },
  {
    id: 'ferr-optimization',
    plan: 'expert',
    routeFr: '/optimisation-ferr',
    routeEn: '/ferr-optimization',
    titleFr: 'Retirer de mon FERR',
    titleEn: 'Withdraw from my RRIF',
    descFr: 'Testez vos retraits FERR pour limiter l’impôt sur plusieurs années.',
    descEn: 'Test RRIF withdrawal strategies to limit taxes over time.',
    icon: 'sliders',
  },
  {
    id: 'multi-source-tax-optimization',
    plan: 'expert',
    routeFr: '/optimisation-fiscale-multi-sources',
    routeEn: '/multi-source-tax-optimization',
    titleFr: 'Payer moins d’impôt à la retraite',
    titleEn: 'Pay less tax in retirement',
    descFr: 'Coordonnez vos retraits et vos revenus pour réduire l’impôt total.',
    descEn: 'Coordinate withdrawals and income sources to reduce total tax.',
    icon: 'calculator',
  },
  {
    id: 'rvdaa',
    plan: 'expert',
    routeFr: '/rvdaa',
    routeEn: '/rvdaa',
    titleFr: 'RVDAA',
    titleEn: 'RVDAA',
    descFr: 'Outil avancé pour tester des scénarios d’épargne et de décaissement.',
    descEn: 'Advanced tool to test savings and decumulation scenarios.',
    icon: 'ruler',
  },
  {
    id: 'withdrawal-sequence',
    plan: 'professional',
    routeFr: '/sequence-retrait',
    routeEn: '/withdrawal-sequence',
    titleFr: 'Quel compte retirer en premier',
    titleEn: 'Which account to withdraw from first',
    descFr: 'Comparez l’ordre de retraits entre vos comptes pour éviter des erreurs coûteuses.',
    descEn: 'Compare withdrawal order across accounts to avoid costly mistakes.',
    icon: 'list-ordered',
  },
  {
    id: 'rrsp-meltdown',
    plan: 'expert',
    routeFr: '/strategies-reer-meltdown',
    routeEn: '/rrsp-meltdown',
    titleFr: 'Réduire mon REER avant qu’il coûte trop cher',
    titleEn: 'Reduce my RRSP before taxes get too high',
    descFr: 'Retirez progressivement de votre REER pour réduire l’impôt futur.',
    descEn: 'Withdraw gradually from your RRSP to reduce future taxes.',
    icon: 'thermometer',
  },
  {
    id: 'cash-wedge-bucket',
    plan: 'professional',
    routeFr: '/module-coussin-liquidites',
    routeEn: '/module-coussin-liquidites',
    titleFr: 'Créer un coussin de liquidités',
    titleEn: 'Build a cash cushion',
    descFr: 'Constituez un coussin pour éviter de vendre vos placements au mauvais moment.',
    descEn: 'Build a cash cushion to avoid selling investments at the wrong time.',
    icon: 'cup-soda',
  },
  {
    id: 'ccq',
    plan: 'professional',
    routeFr: '/retraite-construction',
    routeEn: '/construction-retirement',
    titleFr: 'Retraite dans la construction (CCQ)',
    titleEn: 'Construction retirement (CCQ)',
    descFr: 'Planifiez votre retraite selon les règles de la CCQ et les particularités du milieu de la construction.',
    descEn: 'Plan your retirement with CCQ rules and the realities of the construction industry.',
    icon: 'building-2',
  },
  {
    id: 'succession-planning',
    plan: 'expert',
    routeFr: '/planification-successorale',
    routeEn: '/succession-planning',
    titleFr: 'Préparer ma succession',
    titleEn: 'Prepare my estate',
    descFr: 'Préparez le transfert de patrimoine avec des documents clairs et ordonnés.',
    descEn: 'Prepare an estate transfer with clear and organized documents.',
    icon: 'scroll-text',
  },
];
